### ISSUE TITLE
Finalise paper and documentation

### ISSUE THREAD

**Issue by joelnmdyer** [arnauqb/blackbirds#20]
Express more clearly in the paper "how this software compares to other commonly-used packages in this research area"

**Comment by joelnmdyer** [comment]
Include instructions on the following in the package:

**Community guidelines**

There should be clear guidelines for third-parties wishing to:

- Contribute to the software
- Report issues or problems with the software
- Seek support

**Comment by arnauqb** [comment]
added contributing guidelines in https://github.com/arnauqb/blackbirds/pull/27
