### ISSUE TITLE
Extend API documentation

### ISSUE THREAD

**Issue by marvinschmitt** [arnauqb/blackbirds#44]
@arnauqb This issue is in reference to the JOSS Review https://github.com/openjournals/joss-reviews/issues/5776 

Currently, the documentation website contains the API documentation to the submodules `infer` and `models`. Please also add the API documentation to all remaining functionality (e.g., `blackbirds.simulate`) to the docs.

Furthermore, there is no documentation for some code, such as the entirety of `blackbirds.posterior_estimators`. Please write docstrings and add that to the docs as well.

Thank you!

**Comment by arnauqb** [comment]
Should be addressed in https://github.com/arnauqb/blackbirds/pull/46/commits/6ef774955981b1606f51dc8e5965c56fb0bd60ad as part of https://github.com/arnauqb/blackbirds/pull/46
