### ISSUE TITLE
adjust requirements.txt

### ISSUE THREAD

**Issue by marvinschmitt** [arnauqb/blackbirds#45]
@arnauqb This issue is in reference to the JOSS review https://github.com/openjournals/joss-reviews/issues/5776

Please consider adjusting your [`requirements.txt`](https://github.com/arnauqb/blackbirds/blob/main/requirements.txt) to state `>=` instead of `==`. This decreases the likelihood of unresolvable environment requirements.

This is an optional request. If you have good reasons to stick with `==`, please let me know.

**Comment by arnauqb** [comment]
Fixed in https://github.com/arnauqb/blackbirds/pull/46/commits/2ee98b06c63c5bfd1afc77ec6361955db5625de6
