### ISSUE TITLE
Agent information signal in Rama Cont model

### ISSUE THREAD

**Issue by benjaminpatrickevans** [arnauqb/blackbirds#48]
Hi @arnauqb  and @joelnmdyer.

Thanks for making the repository public!

I have been going through your _Gradient-Assisted Calibration for Financial Agent-Based Models_ paper, and in the implementation of the Rama Cont model, I believe the information signal on [Line 38](https://github.com/arnauqb/blackbirds/blob/81d46b173a221dfd2d53e552f86123c05e0fadea/blackbirds/models/rama_cont.py#L38C9-L38C83):

```python
epsilon_t = torch.distributions.Normal(0, sigma).rsample((self.n_agents,))
```

Should be changed to

```python
epsilon_t = torch.distributions.Normal(0, sigma).rsample()
```

since as per the original paper "agents receive a common signal". The current implementation delivers heterogenous information signals, which may kill some of the intended market dynamics.

Kind regards,
Ben

**Comment by joelnmdyer** [comment]
Thanks @benjaminpatrickevans! Good spot, you're right. We'll update the repository with this change.

Best,
Joel
