### ISSUE TITLE
Shape error in VI

### ISSUE THREAD

**Issue by joelnmdyer** [arnauqb/blackbirds#51]
At https://github.com/arnauqb/blackbirds/blob/0dbe5608188dfd0460f62bec6288429ebeb8e6f9/blackbirds/infer/vi.py#L104 we have

`to_diff += torch.dot(jacobians[i].to(device).to(torch.float), parameters[i, :].to(torch.float))`

which sometimes throws up the shape error

`RuntimeError: 1D tensors expected, but got 2D and 1D tensors`

if you're not careful about ensuring the loss function used produces a scalar tensor. So perhaps we'd better (a) improve this error message to be more informative (e.g., say you need to ensure loss tensor is 0D) or (b) just handle the shape in the Jacobian dot product computations. I guess the former is safer.

**Comment by arnauqb** [comment]
Yes, I would say option (a) is way safer.
